<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('areas')->insert([
            'title' => 'area 1',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Tincidunt arcu non sodales neque sodales ut etiam. Eu turpis egestas pretium aenean pharetra magna. Porttitor eget dolor morbi non. Diam ut venenatis tellus in metus vulputate. Netus et malesuada fames ac turpis egestas sed tempus urna. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. A lacus vestibulum sed arcu non odio euismod lacinia. Proin libero nunc consequat interdum varius sit. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. Arcu dictum varius duis at consectetur lorem donec. A erat nam at lectus urna. Eget magna fermentum iaculis eu.

            Potenti nullam ac tortor vitae purus faucibus ornare. At tellus at urna condimentum mattis. Nunc sed id semper risus in hendrerit gravida. Leo urna molestie at elementum eu. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Sodales neque sodales ut etiam. Neque egestas congue quisque egestas diam in. Metus vulputate eu scelerisque felis imperdiet. Leo urna molestie at elementum eu facilisis sed odio. Lacus luctus accumsan tortor posuere ac. Sit amet nulla facilisi morbi tempus iaculis urna id. Suspendisse in est ante in nibh mauris. Lorem ipsum dolor sit amet consectetur.

            Facilisis gravida neque convallis a. Lectus arcu bibendum at varius vel pharetra. Aliquet eget sit amet tellus cras adipiscing. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Neque aliquam vestibulum morbi blandit cursus risus. Enim nec dui nunc mattis enim. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Lectus urna duis convallis convallis tellus id interdum. Urna condimentum mattis pellentesque id nibh tortor. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Ultrices eros in cursus turpis massa tincidunt. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Sed blandit libero volutpat sed cras ornare arcu. Risus sed vulputate odio ut enim blandit volutpat maecenas. Sem et tortor consequat id.

            Eu nisl nunc mi ipsum faucibus vitae. Vitae congue eu consequat ac felis donec et odio pellentesque. Et odio pellentesque diam volutpat commodo sed egestas. Tempor orci dapibus ultrices in iaculis nunc sed augue. Venenatis urna cursus eget nunc scelerisque viverra. Non quam lacus suspendisse faucibus interdum posuere. Praesent tristique magna sit amet purus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Donec adipiscing tristique risus nec feugiat in fermentum posuere urna. Eget arcu dictum varius duis at consectetur lorem donec. Purus sit amet volutpat consequat mauris nunc congue nisi.

            Volutpat diam ut venenatis tellus in metus vulputate eu. Urna id volutpat lacus laoreet. Dui ut ornare lectus sit amet est placerat. Ac felis donec et odio pellentesque diam volutpat commodo. Integer malesuada nunc vel risus. Sagittis purus sit amet volutpat consequat mauris. A lacus vestibulum sed arcu non odio euismod lacinia at. Faucibus pulvinar elementum integer enim. In egestas erat imperdiet sed euismod nisi. Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Urna condimentum mattis pellentesque id nibh tortor id aliquet. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. In fermentum et sollicitudin ac orci phasellus egestas. Sit amet consectetur adipiscing elit ut aliquam purus sit.

            Pretium quam vulputate dignissim suspendisse in est ante in. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Aenean et tortor at risus viverra adipiscing. Nibh venenatis cras sed felis eget velit. Fusce ut placerat orci nulla pellentesque. Sem fringilla ut morbi tincidunt. Mauris ultrices eros in cursus turpis massa tincidunt. Turpis egestas pretium aenean pharetra magna ac placerat. Faucibus et molestie ac feugiat sed. Platea dictumst vestibulum rhoncus est. Potenti nullam ac tortor vitae. Et netus et malesuada fames ac turpis egestas sed tempus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Ullamcorper morbi tincidunt ornare massa eget egestas. Massa massa ultricies mi quis hendrerit dolor magna eget est. Ac auctor augue mauris augue. Justo eget magna fermentum iaculis eu non diam. In mollis nunc sed id semper risus in hendrerit gravida. Nec ultrices dui sapien eget mi. Placerat in egestas erat imperdiet sed euismod.

            Volutpat est velit egestas dui id ornare arcu. Amet cursus sit amet dictum sit amet. Etiam erat velit scelerisque in dictum. At quis risus sed vulputate odio ut. Donec adipiscing tristique risus nec feugiat. Vel fringilla est ullamcorper eget. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Facilisi nullam vehicula ipsum a. Tortor vitae purus faucibus ornare suspendisse sed nisi. Diam phasellus vestibulum lorem sed risus ultricies. Pharetra sit amet aliquam id diam. Euismod lacinia at quis risus sed vulputate odio. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Tellus pellentesque eu tincidunt tortor aliquam nulla. Fames ac turpis egestas sed tempus urna et.

            Auctor urna nunc id cursus metus aliquam eleifend. Amet porttitor eget dolor morbi non arcu. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Dapibus ultrices in iaculis nunc sed augue. Ullamcorper sit amet risus nullam eget. Netus et malesuada fames ac turpis. Non sodales neque sodales ut etiam. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Rhoncus urna neque viverra justo nec. Magna fermentum iaculis eu non diam phasellus vestibulum. Suspendisse potenti nullam ac tortor vitae purus. Quam id leo in vitae turpis massa sed elementum tempus. Amet facilisis magna etiam tempor orci eu lobortis. Viverra maecenas accumsan lacus vel facilisis. Non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Ultrices dui sapien eget mi. Vestibulum sed arcu non odio euismod lacinia at quis. Sollicitudin tempor id eu nisl. Cras tincidunt lobortis feugiat vivamus.

            Id diam maecenas ultricies mi eget. Potenti nullam ac tortor vitae purus faucibus. Quisque egestas diam in arcu cursus euismod quis. Volutpat diam ut venenatis tellus in metus vulputate. Amet est placerat in egestas erat imperdiet sed euismod nisi. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sed nisi lacus sed viverra tellus in hac habitasse. Habitasse platea dictumst quisque sagittis purus. Commodo viverra maecenas accumsan lacus. Magnis dis parturient montes nascetur ridiculus mus. Lobortis elementum nibh tellus molestie nunc. Est sit amet facilisis magna etiam tempor orci eu lobortis. Ut consequat semper viverra nam libero.

            Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Purus sit amet luctus venenatis lectus. Ut sem nulla pharetra diam sit amet. Sit amet venenatis urna cursus. Eget magna fermentum iaculis eu non. Diam quam nulla porttitor massa id neque. Quis ipsum suspendisse ultrices gravida dictum fusce. Lacus suspendisse faucibus interdum posuere lorem ipsum. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Integer malesuada nunc vel risus commodo. Proin fermentum leo vel orci porta non. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Neque vitae tempus quam pellentesque nec nam aliquam sem et. Commodo viverra maecenas accumsan lacus vel.',
            'imgs' => '[{"layout":"xx","key":"QDjmgmfUUGW8zJrv","attributes":{"image":"ZbwDi68NwnZrnidHHORl1QfWPLgX2ffl1PxUcR06.webp"}},{"layout":"xx","key":"gMJ34y8Z0QAvgva0","attributes":{"image":"Y9ECgme12NMAcLH6rSFK66Yoz4LWJU8YyN60Ty9G.webp"}}]',
            // Add more columns as needed
        ]);
        DB::table('areas')->insert([
            'title' => 'area 51',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Tincidunt arcu non sodales neque sodales ut etiam. Eu turpis egestas pretium aenean pharetra magna. Porttitor eget dolor morbi non. Diam ut venenatis tellus in metus vulputate. Netus et malesuada fames ac turpis egestas sed tempus urna. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. A lacus vestibulum sed arcu non odio euismod lacinia. Proin libero nunc consequat interdum varius sit. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. Arcu dictum varius duis at consectetur lorem donec. A erat nam at lectus urna. Eget magna fermentum iaculis eu.

            Potenti nullam ac tortor vitae purus faucibus ornare. At tellus at urna condimentum mattis. Nunc sed id semper risus in hendrerit gravida. Leo urna molestie at elementum eu. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Sodales neque sodales ut etiam. Neque egestas congue quisque egestas diam in. Metus vulputate eu scelerisque felis imperdiet. Leo urna molestie at elementum eu facilisis sed odio. Lacus luctus accumsan tortor posuere ac. Sit amet nulla facilisi morbi tempus iaculis urna id. Suspendisse in est ante in nibh mauris. Lorem ipsum dolor sit amet consectetur.

            Facilisis gravida neque convallis a. Lectus arcu bibendum at varius vel pharetra. Aliquet eget sit amet tellus cras adipiscing. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Neque aliquam vestibulum morbi blandit cursus risus. Enim nec dui nunc mattis enim. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Lectus urna duis convallis convallis tellus id interdum. Urna condimentum mattis pellentesque id nibh tortor. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Ultrices eros in cursus turpis massa tincidunt. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Sed blandit libero volutpat sed cras ornare arcu. Risus sed vulputate odio ut enim blandit volutpat maecenas. Sem et tortor consequat id.

            Eu nisl nunc mi ipsum faucibus vitae. Vitae congue eu consequat ac felis donec et odio pellentesque. Et odio pellentesque diam volutpat commodo sed egestas. Tempor orci dapibus ultrices in iaculis nunc sed augue. Venenatis urna cursus eget nunc scelerisque viverra. Non quam lacus suspendisse faucibus interdum posuere. Praesent tristique magna sit amet purus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Donec adipiscing tristique risus nec feugiat in fermentum posuere urna. Eget arcu dictum varius duis at consectetur lorem donec. Purus sit amet volutpat consequat mauris nunc congue nisi.

            Volutpat diam ut venenatis tellus in metus vulputate eu. Urna id volutpat lacus laoreet. Dui ut ornare lectus sit amet est placerat. Ac felis donec et odio pellentesque diam volutpat commodo. Integer malesuada nunc vel risus. Sagittis purus sit amet volutpat consequat mauris. A lacus vestibulum sed arcu non odio euismod lacinia at. Faucibus pulvinar elementum integer enim. In egestas erat imperdiet sed euismod nisi. Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Urna condimentum mattis pellentesque id nibh tortor id aliquet. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. In fermentum et sollicitudin ac orci phasellus egestas. Sit amet consectetur adipiscing elit ut aliquam purus sit.

            Pretium quam vulputate dignissim suspendisse in est ante in. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Aenean et tortor at risus viverra adipiscing. Nibh venenatis cras sed felis eget velit. Fusce ut placerat orci nulla pellentesque. Sem fringilla ut morbi tincidunt. Mauris ultrices eros in cursus turpis massa tincidunt. Turpis egestas pretium aenean pharetra magna ac placerat. Faucibus et molestie ac feugiat sed. Platea dictumst vestibulum rhoncus est. Potenti nullam ac tortor vitae. Et netus et malesuada fames ac turpis egestas sed tempus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Ullamcorper morbi tincidunt ornare massa eget egestas. Massa massa ultricies mi quis hendrerit dolor magna eget est. Ac auctor augue mauris augue. Justo eget magna fermentum iaculis eu non diam. In mollis nunc sed id semper risus in hendrerit gravida. Nec ultrices dui sapien eget mi. Placerat in egestas erat imperdiet sed euismod.

            Volutpat est velit egestas dui id ornare arcu. Amet cursus sit amet dictum sit amet. Etiam erat velit scelerisque in dictum. At quis risus sed vulputate odio ut. Donec adipiscing tristique risus nec feugiat. Vel fringilla est ullamcorper eget. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Imperdiet nulla malesuada pellentesque elit eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Facilisi nullam vehicula ipsum a. Tortor vitae purus faucibus ornare suspendisse sed nisi. Diam phasellus vestibulum lorem sed risus ultricies. Pharetra sit amet aliquam id diam. Euismod lacinia at quis risus sed vulputate odio. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Tellus pellentesque eu tincidunt tortor aliquam nulla. Fames ac turpis egestas sed tempus urna et.

            Auctor urna nunc id cursus metus aliquam eleifend. Amet porttitor eget dolor morbi non arcu. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Dapibus ultrices in iaculis nunc sed augue. Ullamcorper sit amet risus nullam eget. Netus et malesuada fames ac turpis. Non sodales neque sodales ut etiam. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Rhoncus urna neque viverra justo nec. Magna fermentum iaculis eu non diam phasellus vestibulum. Suspendisse potenti nullam ac tortor vitae purus. Quam id leo in vitae turpis massa sed elementum tempus. Amet facilisis magna etiam tempor orci eu lobortis. Viverra maecenas accumsan lacus vel facilisis. Non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Ultrices dui sapien eget mi. Vestibulum sed arcu non odio euismod lacinia at quis. Sollicitudin tempor id eu nisl. Cras tincidunt lobortis feugiat vivamus.

            Id diam maecenas ultricies mi eget. Potenti nullam ac tortor vitae purus faucibus. Quisque egestas diam in arcu cursus euismod quis. Volutpat diam ut venenatis tellus in metus vulputate. Amet est placerat in egestas erat imperdiet sed euismod nisi. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sed nisi lacus sed viverra tellus in hac habitasse. Habitasse platea dictumst quisque sagittis purus. Commodo viverra maecenas accumsan lacus. Magnis dis parturient montes nascetur ridiculus mus. Lobortis elementum nibh tellus molestie nunc. Est sit amet facilisis magna etiam tempor orci eu lobortis. Ut consequat semper viverra nam libero.

            Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Purus sit amet luctus venenatis lectus. Ut sem nulla pharetra diam sit amet. Sit amet venenatis urna cursus. Eget magna fermentum iaculis eu non. Diam quam nulla porttitor massa id neque. Quis ipsum suspendisse ultrices gravida dictum fusce. Lacus suspendisse faucibus interdum posuere lorem ipsum. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Integer malesuada nunc vel risus commodo. Proin fermentum leo vel orci porta non. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Neque vitae tempus quam pellentesque nec nam aliquam sem et. Commodo viverra maecenas accumsan lacus vel.',
            'imgs' => '[{"layout":"xx","key":"7N2XvnzANVl8J0We","attributes":{"image":"Gx9ows49GIEPHuDB8qdfz9MHUIadK2cslv0ZhiA0.png"}},{"layout":"xx","key":"aYxe0J6EzfaMFX8x","attributes":{"image":"osKYGuabxrtb3AZsJ78MXLTvbfrzxn5kZCDojLMh.webp"}}]',
            // Add more columns as needed
        ]);
    }
}
